### ISSUE TITLE
Could not validate sizes - Operation not permitted

### ISSUE THREAD

**Issue by richb-hanover** [midi1996/hackintosh-internet-install-gitbook#11]
Using macOS 10.15.3 to create an installer USB drive according to https://internet-install.gitbook.io/macos-internet-install/preparing-your-installer/preparing-your-installer-media.

The process goes as described until I get to step 7 & 8 of the Disk Utility ("Select Restore" and "Choose BaseSystem..."). Then I encounter the error message below 

What other information could I provide to debug this? Thanks.

<img width="442" alt="image" src="https://user-images.githubusercontent.com/1094930/77598167-7a791100-6ed7-11ea-9f59-6af5ba0073b1.png">

Here's the text from the image if you can't read it...
```
Restoring "Installer" from "macOS Base System"

Validating target...
Validating source...
Validating sizes...
Could not validate sizes - Operation not permitted
The operation couldn't be completed. (OSStatus error 1.)
Operation failed...
```

**Comment by midi1996** [comment]
🤔 Either the image is not properly made or macOS has an issue with the USB.

I would suggest you to:
- Redownload the recovery
- Try using a linux system to make that setup (or the linux method on macOS, can be done)
- Try using windows to make the setup (windows 10 1709+)

Other than that, I moved to OpenCore now, there is also no real need to write the image to the usb, just a copy-paste with some folder structure. Good Luck.

**Comment by richb-hanover** [comment]
> ... Other than that, I moved to OpenCore now, there is also no real need to write the image to the usb, just a copy-paste with some folder structure. Good Luck.

Do you think OpenCore is stable enough for non-fanatics to use? I just want to get a simple Hackintosh going... Thanks.

**Comment by midi1996** [comment]
What do you mean by "non-fanatics", it's either you use it or not, it's not about being fanatic (???). It's  been good ever since last september. (I've been using it ever since 0.0.1 release). And if you're looking for a "Simple hackintosh", you're doing it wrong. remember that you're running an OS on unofficial hardware.

**Comment by richb-hanover** [comment]
Sorry - I was being glib. And I do take to heart your advice that all this is a totally unofficial software on unsupported hardware...

I guess my real question is whether (the inevitable) problems I encounter when installing the Hackintosh are likely to be my own procedure/kexts/etc, or whether I will need to worry about (or track down) an OpenCore problem.

It sounds to me as if OpenCore is now good enough for more general use - that is, I'm not going to trip over many OpenCore bugs on the way. Thank you.
