### ISSUE TITLE
How to setup up authentication proxy before setup

### ISSUE THREAD

**Issue by RRC07** [midi1996/hackintosh-internet-install-gitbook#6]
Hello,
I've successfully booted my USB using your guide. All others were stuck at scanning for entries while loading Clover.
But I am a student, and my network works under an authentication proxy. I googled around a bit to find out that I could do this via networksetup command through the terminal, but I think that is deprecated and it shows "Command not found."
Please help. Thanks.

**Comment by midi1996** [comment]
Sorry, no idea, you can try sharing your internet from another device that is properly connected (laptop, phone, router...) but I can't help with weirdly configured networks.
